# Generated by Django 5.0.6 on 2024-06-06 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='区号')),
                ('area_name', models.CharField(max_length=20, unique=True, verbose_name='分区名称')),
                ('price_ph', models.IntegerField(verbose_name='每小时单价')),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='CafeAdmin',
            fields=[
                ('admin_acct', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='管理员账户')),
                ('admin_pwd', models.CharField(max_length=20, verbose_name='管理员密码')),
                ('admin_name', models.CharField(max_length=20, unique=True, verbose_name='管理员姓名')),
                ('phone_name', models.CharField(max_length=20, unique=True, verbose_name='联系方式')),
            ],
            options={
                'db_table': 'cafe_admin',
            },
        ),
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('comp_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='机号')),
                ('status', models.BooleanField(default=0, null=0, verbose_name='状态')),
                ('admin_acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cafeadmin', verbose_name='管理员账号')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.area', verbose_name='所在区号')),
            ],
            options={
                'db_table': 'computer',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('ID_number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('pwd', models.CharField(max_length=20, unique=True, verbose_name='密码')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='账户余额')),
                ('reg_time', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('admin_acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cafeadmin', verbose_name='管理员账号')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='上机时间')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='下机时间')),
                ('to_pay', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='消费金额')),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.comp', verbose_name='机号')),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.userinfo', verbose_name='身份证号')),
            ],
            options={
                'db_table': 'pay_record',
            },
        ),
        migrations.AddField(
            model_name='comp',
            name='user_comp',
            field=models.ManyToManyField(through='apps.PayRecord', to='apps.userinfo'),
        ),
        migrations.CreateModel(
            name='RcgRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcg_time', models.DateTimeField(auto_now_add=True, verbose_name='充值时间')),
                ('rcg_meth', models.CharField(max_length=20, verbose_name='充值方式')),
                ('rcg_fig', models.IntegerField(verbose_name='充值金额')),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.userinfo', verbose_name='身份证号')),
            ],
            options={
                'db_table': 'rcg_record',
                'unique_together': {('id_number', 'rcg_time')},
            },
        ),
    ]
