# Generated by Django 5.0.6 on 2024-06-10 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='admin_acct',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apps.cafeadmin', verbose_name='管理员账号'),
        ),
    ]
