# Generated by Django 5.0.6 on 2024-06-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_userinfo_admin_acct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rcgrecord',
            unique_together=set(),
        ),
    ]
