# Generated by Django 5.0.6 on 2024-06-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_rcgrecord_rcg_meth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='status',
            field=models.BooleanField(choices=[(0, '空闲'), (1, '忙碌')], default=0, null=0, verbose_name='状态'),
        ),
    ]
